# Generated by Django 6.0.6 on 2026-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='correct_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
