# Generated by Django 6.0.6 on 2026-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewresult_correct_answer_interviewresult_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='correct_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
