# Generated by Django 6.0.6 on 2026-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interviewresult_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
